version: '2'
services:
  rancher-purge:
    image: wmbutler/rancher-purge
    environment:
      RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
      RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
      RANCHER_URL: ${RANCHER_URL}
      RANCHER_ENVIRONMENT: ${RANCHER_URL}
      INTERVAL: 180
